apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-2i538d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2i538d
  namespace: my-nginx-2i538d
  labels:
    name: nginx-2i538d
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-2i538d
  template:
    metadata:
      namespace: my-nginx-2i538d
      labels:
        name: nginx-2i538d
    spec:
      containers:
      - name: nginx-2i538d
        image: nginx
        ports:
        - containerPort: 80

